### ISSUE TITLE
знайдені проблеми

### ISSUE THREAD

**Issue by ipiwebtech** [VitaBrrevis/VitaBrrevis.github.io#1]
<img width="960" alt="missed" src="https://github.com/VitaBrrevis/VitaBrrevis.github.io/assets/129291207/4723c51c-09d8-42fb-892d-facaa0204c49">
не вистачає по одному блоку в хедері і футері, гляньте уважно завдання вашого варіанту

**Comment by ipiwebtech** [comment]
<img width="469" alt="scroll" src="https://github.com/VitaBrrevis/VitaBrrevis.github.io/assets/129291207/200d3d3f-8dab-4965-ae00-63fe06d17096">
появилась смуга гориз.прокрутки при ресайзі вікна броузера

**Comment by ipiwebtech** [comment]
зникла частина тексту в колонці, її не видно
<img width="950" alt="missed-text" src="https://github.com/VitaBrrevis/VitaBrrevis.github.io/assets/129291207/f9abd7e5-e123-4de5-bc98-3401113656bb">

**Comment by VitaBrrevis** [comment]
Ніби виправила. Дякую за зауваження!!!!!!
